### PR TITLE
Dynamic memory improvements

### PR DESCRIPTION
**Pull request by ajaybhargav**
I have added wrapper functions for systems with inbuilt memory allocators. e.g. many embedded system does provide alloc/free functions. however they cannot directly fit in current dynamic memory layer. I also added some abstraction to memory layer so one can easily write his/her own allocator if needed or use the three provided allocators:
1. DYN_MEM_SIMPLE : previously defined as DYN_MEM
2. DYN_MEM_DEFR : allocator with de-fragmentation
3. DYN_MEM_CUST: for systems with memory allocator functions available (e.g. malloc/free).

Please go through the patches and see if you feel they are useful then you can merge them.

I have already tested DYN_MEM_CUST on  my system. It works fine.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Your implementation look great! However according to your previous suggestion I implemented the possibility of using normal malloc/free. Currently I am testing it, but I'm planning  to release it in the next week. (To use the normal malloc/free the core of the library has to be changed too.)

Your version is also great I will think about it!

Thanks!

**Comment by ajaybhargav** [comment]
Thanks! I had an initial though of going with malloc/free, There is a reason i made this commit.
There is no way to get size of malloced area from its pointer which is needed by lvgl core (dm_get_size) so having a wrapper around normal malloc/free we can get this function working.
secondly, There many embedded systems which only support malloc/free type of function but no realloc. So dm_realloc also solve that purpose. So by just having two base allocator functions we can have library working without any problem.
Abstraction is an added advantage as there is no need of change in lvgl core. If you want I can send pull request on beta branch.

**Comment by kisvegabor** [comment]
Yes, the problem was the dm_get_size. But I could change the library to work without this function. Now misc_conf looks like this:
```
#define USE_DYN_MEM     0
#if USE_DYN_MEM != 0
#define DM_MEM_SIZE    (16U * 1024U) /*Size memory used by mem_alloc (in bytes)*/
#define DM_AUTO_ZERO   1             /*Automatically fill-zero the allocated memory*/
#define DM_MEM_ATTR                   /*Complier prefix for big array declaration*/
#else /*Add wrappers to normal malloc/free/realloc */
#define DM_INCLUDE <stdlib.h>   /*Header for the dynamic memory function*/
#define dm_alloc   malloc
#define dm_free    free
#define dm_realloc realloc
#endif  /*USE_DYN_MEM*/
```
You are right with realloc, it is not available on every systems. I try to figure out something to eliminate this.

**Comment by ajaybhargav** [comment]
It will be great if you can stick to malloc/free only. There are only three areas where realloc is used obj/chart/img which can be fixed easily and adding another variable to lv_obj_t which can store the size of style will also remove the need of dm_get_size. So we are good to go with malloc/free only.

**Comment by kisvegabor** [comment]
I saw in 'dyn_mem_cust.c' you are building a linked list from the allocated memories but it I don't know why is it necessary. Can you explain it?

**Comment by ajaybhargav** [comment]
Actually it's not needed. I just realized :) my previous implementation was different that's why I added that linked list thing. But now I feel it's not needed at all since I am creating header +memory pointer from same alloced area. I will have to recreate the patch. But you get the idea right.there will be no need of making changes to the core.

**Comment by ajaybhargav** [comment]
I am closing this pull request.

**Pull request closed without merging**
